site_name: "CacheMatic"
site_url: https://maximyudayev.github.io/CacheMatic
site_author: Maxim Yudayev
site_description: >-
  Architecture overview, user guides and tutorials for the use of CacheMatic
  open-source cache subsystem generator in Chisel lang for RISC-V processors with OpenRAM
copyright: Copyright &copy; 2025 Maxim Yudayev

# Will inject a GitHub stats link in top navigation bar
repo_name: maximyudayev/CacheMatic
repo_url: https://github.com/maximyudayev/CacheMatic

# Site structure
nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/index.md
  - Getting started:
    - firststeps/index.md
    - Changelog: firststeps/changelog.md
    - License: firststeps/license.md
    - Contributing: firststeps/contributing.md
    - "Tutorials":
      - firststeps/tutorials/index.md
      - Multi-hart: firststeps/tutorials/multihart.md
  - Help desk:
    - Current limitations: helpdesk/limitations.md
    - Known issues: helpdesk/issues.md
    - Roadmap: helpdesk/roadmap.md
    - FAQs: helpdesk/faq.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  favicon_light: assets/favicon_light.png
  favicon_dark: assets/favicon_dark.png
  logo_light: assets/logo_light.png
  logo_dark: assets/logo_dark.png
  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - toc.follow
    # - search.highlight
    # - search.share
    - search.suggest
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Open Sans
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maximyudayev/CacheMatic
    - icon: fontawesome/brands/linkedin-in
      link: https://linkedin.com/in/maxim-yudayev
    - icon: octicons/globe-24
      link: https://yudayev.com

markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: true
      permalink_title: Anchor link to this section for reference
  - footnotes
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
